import { IconWrapper } from '../IconWrapper';

import { Account as AccountSvg } from './svgs/Account';
import { AlertBox as AlertBoxSvg } from './svgs/AlertBox';
import { AlertBoxOutline as AlertBoxOutlineSvg } from './svgs/AlertBoxOutline';
import { AlertCircleOutline as AlertCircleOutlineSvg } from './svgs/AlertCircleOutline';
import { Application as ApplicationSvg } from './svgs/Application';
import { ApplicationBrackets as ApplicationBracketsSvg } from './svgs/ApplicationBrackets';
import { ApplicationCogOutline as ApplicationCogOutlineSvg } from './svgs/ApplicationCogOutline';
import { At as AtSvg } from './svgs/At';
import { Backburger as BackburgerSvg } from './svgs/Backburger';
import { BadgeAccount as BadgeAccountSvg } from './svgs/BadgeAccount';
import { Bell as BellSvg } from './svgs/Bell';
import { BellRing as BellRingSvg } from './svgs/BellRing';
import { CarBrakeParking as CarBrakeParkingSvg } from './svgs/CarBrakeParking';
import { Check as CheckSvg } from './svgs/Check';
import { CheckboxBlankOutline as CheckboxBlankOutlineSvg } from './svgs/CheckboxBlankOutline';
import { CheckboxIntermediateVariant as CheckboxIntermediateVariantSvg } from './svgs/CheckboxIntermediateVariant';
import { CheckboxMarked as CheckboxMarkedSvg } from './svgs/CheckboxMarked';
import { CheckDecagram as CheckDecagramSvg } from './svgs/CheckDecagram';
import { CheckDecagramOutline as CheckDecagramOutlineSvg } from './svgs/CheckDecagramOutline';
import { ChevronDown as ChevronDownSvg } from './svgs/ChevronDown';
import { ChevronUp as ChevronUpSvg } from './svgs/ChevronUp';
import { Circle as CircleSvg } from './svgs/Circle';
import { Close as CloseSvg } from './svgs/Close';
import { Code as CodeSvg } from './svgs/Code';
import { ContentCopy as ContentCopySvg } from './svgs/ContentCopy';
import { Cookie as CookieSvg } from './svgs/Cookie';
import { Dialpad as DialpadSvg } from './svgs/Dialpad';
import { Earth as EarthSvg } from './svgs/Earth';
import { EmailOutline as EmailOutlineSvg } from './svgs/EmailOutline';
import { ExitToApp as ExitToAppSvg } from './svgs/ExitToApp';
import { Eye as EyeSvg } from './svgs/Eye';
import { EyeOffOutline as EyeOffOutlineSvg } from './svgs/EyeOffOutline';
import { EyeOutline as EyeOutlineSvg } from './svgs/EyeOutline';
import { FlagCheckered as FlagCheckeredSvg } from './svgs/FlagCheckered';
import { FolderRemoveOutline as FolderRemoveOutlineSvg } from './svgs/FolderRemoveOutline';
import { FormTextboxPassword as FormTextboxPasswordSvg } from './svgs/FormTextboxPassword';
import { Github as GithubSvg } from './svgs/Github';
import { HelpCircle as HelpCircleSvg } from './svgs/HelpCircle';
import { History as HistorySvg } from './svgs/History';
import { Information as InformationSvg } from './svgs/Information';
import { KeyIconFilled as KeyIconFilledSvg } from './svgs/KeyIconFilled';
import { KeyIconOutlined as KeyIconOutlinedSvg } from './svgs/KeyIconOutlined';
import { KIcon as KIconSvg } from './svgs/KIcon';
import { LeadingIcon as LeadingIconSvg } from './svgs/LeadingIcon';
import { Link as LinkSvg } from './svgs/Link';
import { Linkedin as LinkedinSvg } from './svgs/Linkedin';
import { Loading as LoadingSvg } from './svgs/Loading';
import { Magnify as MagnifySvg } from './svgs/Magnify';
import { MapMarker as MapMarkerSvg } from './svgs/MapMarker';
import { MenuOpen as MenuOpenSvg } from './svgs/MenuOpen';
import { Plus as PlusSvg } from './svgs/Plus';
import { ProgressWrench as ProgressWrenchSvg } from './svgs/ProgressWrench';
import { QrcodeScan as QrcodeScanSvg } from './svgs/QrcodeScan';
import { RadioboxBlank as RadioboxBlankSvg } from './svgs/RadioboxBlank';
import { RadioboxMarked as RadioboxMarkedSvg } from './svgs/RadioboxMarked';
import { Refresh as RefreshSvg } from './svgs/Refresh';
import { ScriptTextKey as ScriptTextKeySvg } from './svgs/ScriptTextKey';
import { ScriptTextKeyNew as ScriptTextKeyNewSvg } from './svgs/ScriptTextKeyNew';
import { ShieldAccountVariantOutline as ShieldAccountVariantOutlineSvg } from './svgs/ShieldAccountVariantOutline';
import { SignatureFreehand as SignatureFreehandSvg } from './svgs/SignatureFreehand';
import { SlashForward as SlashForwardSvg } from './svgs/SlashForward';
import { StopCircle as StopCircleSvg } from './svgs/StopCircle';
import { ThemeLightDark as ThemeLightDarkSvg } from './svgs/ThemeLightDark';
import { TrailingIcon as TrailingIconSvg } from './svgs/TrailingIcon';
import { Transition as TransitionSvg } from './svgs/Transition';
import { TransitionMasked as TransitionMaskedSvg } from './svgs/TransitionMasked';
import { Twitter as TwitterSvg } from './svgs/Twitter';
import { UsbFlashDrive as UsbFlashDriveSvg } from './svgs/UsbFlashDrive';

export const Account = IconWrapper(AccountSvg);
export const AlertBox = IconWrapper(AlertBoxSvg);
export const AlertBoxOutline = IconWrapper(AlertBoxOutlineSvg);
export const AlertCircleOutline = IconWrapper(AlertCircleOutlineSvg);
export const Application = IconWrapper(ApplicationSvg);
export const ApplicationBrackets = IconWrapper(ApplicationBracketsSvg);
export const ApplicationCogOutline = IconWrapper(ApplicationCogOutlineSvg);
export const At = IconWrapper(AtSvg);
export const Backburger = IconWrapper(BackburgerSvg);
export const BadgeAccount = IconWrapper(BadgeAccountSvg);
export const Bell = IconWrapper(BellSvg);
export const BellRing = IconWrapper(BellRingSvg);
export const CarBrakeParking = IconWrapper(CarBrakeParkingSvg);
export const Check = IconWrapper(CheckSvg);
export const CheckboxBlankOutline = IconWrapper(CheckboxBlankOutlineSvg);
export const CheckboxIntermediateVariant = IconWrapper(
  CheckboxIntermediateVariantSvg,
);
export const CheckboxMarked = IconWrapper(CheckboxMarkedSvg);
export const CheckDecagram = IconWrapper(CheckDecagramSvg);
export const CheckDecagramOutline = IconWrapper(CheckDecagramOutlineSvg);
export const ChevronDown = IconWrapper(ChevronDownSvg);
export const ChevronUp = IconWrapper(ChevronUpSvg);
export const Close = IconWrapper(CloseSvg);
export const Code = IconWrapper(CodeSvg);
export const Cookie = IconWrapper(CookieSvg);
export const ContentCopy = IconWrapper(ContentCopySvg);
export const Dialpad = IconWrapper(DialpadSvg);
export const Earth = IconWrapper(EarthSvg);
export const EmailOutline = IconWrapper(EmailOutlineSvg);
export const ExitToApp = IconWrapper(ExitToAppSvg);
export const Eye = IconWrapper(EyeSvg);
export const EyeOffOutline = IconWrapper(EyeOffOutlineSvg);
export const EyeOutline = IconWrapper(EyeOutlineSvg);
export const FlagCheckered = IconWrapper(FlagCheckeredSvg);
export const FolderRemoveOutline = IconWrapper(FolderRemoveOutlineSvg);
export const FormTextboxPassword = IconWrapper(FormTextboxPasswordSvg);
export const Github = IconWrapper(GithubSvg);
export const HelpCircle = IconWrapper(HelpCircleSvg);
export const History = IconWrapper(HistorySvg);
export const Information = IconWrapper(InformationSvg);
export const KeyIconFilled = IconWrapper(KeyIconFilledSvg);
export const KeyIconOutlined = IconWrapper(KeyIconOutlinedSvg);
export const KIcon = IconWrapper(KIconSvg);
export const LeadingIcon = IconWrapper(LeadingIconSvg);
export const Link = IconWrapper(LinkSvg);
export const Linkedin = IconWrapper(LinkedinSvg);
export const Loading = IconWrapper(LoadingSvg);
export const Magnify = IconWrapper(MagnifySvg);
export const MapMarker = IconWrapper(MapMarkerSvg);
export const MenuOpen = IconWrapper(MenuOpenSvg);
export const Plus = IconWrapper(PlusSvg);
export const ProgressWrench = IconWrapper(ProgressWrenchSvg);
export const QrcodeScan = IconWrapper(QrcodeScanSvg);
export const RadioboxBlank = IconWrapper(RadioboxBlankSvg);
export const RadioboxMarked = IconWrapper(RadioboxMarkedSvg);
export const Refresh = IconWrapper(RefreshSvg);
export const ScriptTextKey = IconWrapper(ScriptTextKeySvg);
export const ScriptTextKeyNew = IconWrapper(ScriptTextKeyNewSvg);
export const ShieldAccountVariantOutline = IconWrapper(
  ShieldAccountVariantOutlineSvg,
);
export const SignatureFreehand = IconWrapper(SignatureFreehandSvg);
export const SlashForward = IconWrapper(SlashForwardSvg);
export const StopCircle = IconWrapper(StopCircleSvg);
export const ThemeLightDark = IconWrapper(ThemeLightDarkSvg);
export const TrailingIcon = IconWrapper(TrailingIconSvg);
export const Twitter = IconWrapper(TwitterSvg);
export const UsbFlashDrive = IconWrapper(UsbFlashDriveSvg);
export const Circle = IconWrapper(CircleSvg);
export const Transition = IconWrapper(TransitionSvg);
export const TransitionMasked = IconWrapper(TransitionMaskedSvg);
