const URL = process.env.NEXT_PUBLIC_URL;
const TRACKING_ID = process.env.NEXT_PUBLIC_TRACKING_ID;
const SUPABASE_PROJECT_URL = process.env.NEXT_PUBLIC_SUPABASE_PROJECT_URL;
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

if (!URL) console.error('NEXT_PUBLIC_URL is not set');
if (!TRACKING_ID) console.error('NEXT_PUBLIC_TRACKING_ID is not set');
if (!SUPABASE_PROJECT_URL)
  console.error('NEXT_PUBLIC_SUPABASE_PROJECT_URL is not set');
if (!SUPABASE_PUBLISHABLE_KEY)
  console.error('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY is not set');

export const env = {
  URL,
  TRACKING_ID: TRACKING_ID ?? '',
  SUPABASE_PROJECT_URL: SUPABASE_PROJECT_URL ?? '',
  SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ?? '',
} as const;
