version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: 'Europe/Amsterdam'
    target-branch: main
    groups:
      monorepo-tooling:
        patterns:
          - '*'
    allow:
      # Only allow updates for specific packages, due to https://github.com/dependabot/dependabot-core/issues/4364.
      - dependency-name: "@changesets/cli"
      - dependency-name: "knip"
      - dependency-name: "only-allow"
      - dependency-name: "prettier-plugin-organize-imports"
      - dependency-name: "prettier-plugin-packagejson"
      - dependency-name: "syncpack"
      - dependency-name: "tsx"
      - dependency-name: "turbo"
    reviewers:
      - 'ghislain89'
      - 'alber70g'
    open-pull-requests-limit: 1
