#!/bin/bash
set -o errexit  # abort on nonzero exitstatus
set -o nounset  # abort on unbound variable
set -o pipefail # don't hide errors within pipes
# set -o xtrace   # show commands and expand variables
trap 'catch $? $LINENO' EXIT
catch() {
  if [ "$1" != "0" ]; then
    # error handling goes here
    echo "Error $1 occurred on $2"
  fi
}

cwd=$(pwd)

# Invoke preinstalled packages from the autoinstaller "rush-command-packages"
# Invokes "lint-staged" in all projects
node common/scripts/install-run-rush.js lint-staged || exit $?
