const MAINTENANCE_STARTDATE = import.meta.env.VITE_MAINTENANCE_STARTDATE;
const MAINTENANCE_ENDDATE = import.meta.env.VITE_MAINTENANCE_ENDDATE;
const MAINTENANCE_MESSAGE = import.meta.env.VITE_MAINTENANCE_MESSAGE;

console.log(MAINTENANCE_STARTDATE);

export const env = {
  MAINTENANCE_STARTDATE: MAINTENANCE_STARTDATE
    ? parseInt(MAINTENANCE_STARTDATE)
    : undefined,
  MAINTENANCE_ENDDATE: MAINTENANCE_ENDDATE
    ? parseInt(MAINTENANCE_ENDDATE)
    : undefined,
  MAINTENANCE_MESSAGE,
} as const;
