name: 'Runner setup'
runs:
  using: 'composite'
  steps:
      # TODO: verify usage of github actions cache instead of TurboRepo remote caching
      # - name: Cache turbo build setup
      #   uses: actions/cache@v4
      #   with:
      #     path: .turbo
      #     key: ${{ runner.os }}-turbo-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        shell: bash
        run: pnpm install
