name: Bug report
description: Report an issue with Kadena
labels:
  - bug
body:
  - type: markdown
    attributes:
      value:
        Thank you for taking the time to file a bug report. Please fill out this
        form as completely as possible.

  - type: checkboxes
    id: initial-checks
    attributes:
      label: 'Please confirm the following:'
      options:
        - label:
            I have read the [Code of
            Conduct](https://github.com/kadena-community/kadena.js/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: The bug was not reported before
          required: true
        - label: I am using the **latest version** of the relevant package(s)
          required: true

  - type: input
    id: os
    attributes:
      label: What operating system are you using?
      placeholder: Mac, Windows, Linux
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: What browser are you using? Please add the version as well.
      placeholder: Chrome, Firefox, Safari
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Steps to reproduce the behavior
      description:
        A clear and concise description how to reproduce the error. It helps to
        add screenshots/videos/gifs.
    validations:
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: Steps to reproduce the behavior
      description:
        A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: checkboxes
    id: willing-to-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false
