name: Feature request
description: Suggest an idea for this project
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value:
        Thank you for taking the time to request a new feature. Please fill out
        this form as completely as possible.

  - type: checkboxes
    id: initial-checks
    attributes:
      label: 'Please confirm the following:'
      options:
        - label:
            I have read the [Code of
            Conduct](https://github.com/kadena-community/kadena.js/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: The feature was not suggested before
          required: true

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description:
        A clear and concise description of what the problem is. E.g. I'm always
        frustrated when [...]

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description:
        A clear and concise description of any alternative solutions or features
        you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Do you have any additional context?
      description:
        Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: willing-to-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this feature request.
          required: false
