name: Improve documentation
description: Make a suggestion to improve the content in an existing article.
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        * For questions, ask in [Discord](https://discord.io/kadena).
        * Before you file an issue read the [Contributing guide](https://github.com/kadena-community/kadena.js/blob/master/CONTRIBUTING.md).
        * Check to make sure someone hasn't already opened a similar [issues](https://github.com/kadena-community/kadena.js/issues).

  - type: textarea
    attributes:
      label: What article is affected?
      description: Please link to the article you'd like to see updated.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What part(s) of the article would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see.
        - Why should the docs be changed? What use cases does it support?
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
