name: 'Start Kadena sandbox'
description: 'Start a Kadena Devnet environment using docker-compose with indexer components'
runs:
  using: 'composite'
  steps:
    - name: Start sandbox
      shell: bash
      run: |
        git clone --depth=1 -b ag/kadena-js-devnet git@github.com:kadena-io/devnet.git
        cd devnet && docker compose -f docker-compose.indexer.yaml up -d --quiet-pull
      working-directory: .github/actions/sandbox

    - name: Check sandbox health
      shell: bash
      run: ./healthcheck.sh
      working-directory: .github/actions/sandbox
