name: 'Start Blockchain Sandbox'
runs:
  using: 'composite'
  steps:
    - name: Start sandbox
      shell: bash
      run: docker-compose up -d

    - name: Check sandbox health
      shell: bash
      run: ./healthcheck.sh
