name: 'Start Kadena sandbox'
description: 'Start a Kadena Devnet environment using docker-compose with indexer components'
runs:
  using: 'composite'
  steps:
    - name: Start sandbox
      shell: bash
      run: docker compose up -d
      working-directory: .github/actions/sandbox

    - name: Check sandbox health
      shell: bash
      run: ./healthcheck.sh
      working-directory: .github/actions/sandbox