version: "3.9"

services:
  # Common chainweb node spec
  node:
    image: ${CHAINWEB_NODE_IMAGE:-ghcr.io/kadena-io/chainweb-node/ubuntu:latest}
    restart: unless-stopped
    stop_grace_period: 20s
    stop_signal: SIGINT
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    expose:
      - "1789"
      - "1848"
    entrypoint:
      - /chainweb/chainweb-node
      # Runtime Settings
      - +RTS
      - -T
      - -H400M
      - -A64M
      - -RTS
      # Common Configuration
      - --config-file=config/chainweb-node.common.yaml
      - --config-file=config/chainweb-node.logging.yaml
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        delay: 60s
        order: stop-first
    healthcheck:
      test: 
        - 'CMD'
        - '/bin/bash'
        - '-c'
        - 'exec 3<>/dev/tcp/localhost/1848; printf "GET /health-check HTTP/1.1\r\nhost: http://localhost:1848\r\nConnection: close\r\n\r\n" >&3; grep -q "200 OK" <&3 || exit 1'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m