import { IMenuItem } from '@/types/Layout';

export const leftMenuTree: IMenuItem[] = [
  {
    root: '/docs/kadena',
    title: 'Intro to Kadena',
    menu: 'Kadena',
    label: 'Introduction',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/build',
    title: 'Build on Kadena',
    menu: 'Build',
    label: 'Introduction',
    icon: 'Contribute',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/pact',
    title: 'Learn Pact',
    menu: 'Pact',
    label: 'Pact',
    icon: 'PactDeveloper',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/contribute',
    title: 'Contribute',
    menu: 'Contribute',
    label: 'Contribute',
    icon: 'Contribute',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/chainweb',
    title: 'Intro to Chainweb',
    menu: 'Chainweb',
    label: 'Introduction',
    icon: 'Chainweb',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/marmalade',
    title: 'Intro to Marmalade',
    menu: 'Marmalade',
    label: 's',
    icon: 'Marmalade',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
];
