import type { IMenuItem } from '@/Layout';

export const leftMenuTree: IMenuItem[] = [
  {
    root: '/docs/kadena',
    title: 'Intro to Kadena',
    menu: 'Kadena',
    label: 'Introduction',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/build',
    title: 'Build on Kadena',
    menu: 'Build',
    label: 'Introduction',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/pact',
    title: 'Learn Pact',
    menu: 'Pact',
    label: 'Pact',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/contribute',
    title: 'Contribute',
    menu: 'Contribute',
    label: 'Contribute',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/chainweb',
    title: 'Intro to Chainweb',
    menu: 'Chainweb',
    label: 'Introduction',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/marmalade',
    title: 'Intro to Marmalade',
    menu: 'Marmalade',
    label: 's',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
];

export const fullLayoutLeftMenuTree: IMenuItem[] = [
  {
    children: [
      {
        children: [],
        root: '/docs/kadena/overview',
        title: 'Overview of Kadena',
        menu: 'Kadena',
        label: 'Overview',
        isMenuOpen: true,
        isActive: true,
      },
      {
        children: [
          {
            children: [],
            root: '/docs/kadena/kda/manage-kda',
            title: 'Manage KDA',
            menu: 'Manage KDA',
            label: 'Manage KDA',
            isMenuOpen: false,
            isActive: false,
          },
          {
            children: [],
            root: '/docs/kadena/kda/kda-concepts',
            title: 'KDA Concepts',
            menu: 'KDA Concepts',
            label: 'KDA Concepts',
            isMenuOpen: false,
            isActive: false,
          },
        ],
        root: '/docs/kadena/kda',
        title: 'What is KDA?',
        menu: 'KDA',
        label: 'What is KDA?',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [
          {
            children: [],
            root: '/docs/kadena/whitepapers/chainweb-layer-1',
            title: 'Chainweb Layer 1',
            menu: 'Whitepapers',
            label: 'Chainweb Layer 1',
            isMenuOpen: false,
            isActive: false,
          },
          {
            children: [],
            root: '/docs/kadena/whitepapers/pact-smart-contract-language',
            title: 'Pact Smart Contract Language',
            menu: 'Whitepapers',
            label: 'Pact Smart Contract',
            isMenuOpen: false,
            isActive: false,
          },
          {
            children: [],
            root: '/docs/kadena/whitepapers/kuro-layer-2',
            title: 'Kuro Layer 2',
            menu: 'Whitepapers',
            label: 'Kuro Layer 2',
            isMenuOpen: false,
            isActive: false,
          },
        ],
        root: '/docs/kadena/whitepapers',
        title: 'Whitepapers Overview',
        menu: 'Whitepapers',
        label: 'Overview',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/wallets',
        title: 'Kadena Wallets',
        menu: 'Kadena Wallets',
        label: 'Overview',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/exchanges',
        title: 'Kadena Exchanges',
        menu: 'Exchanges',
        label: 'Exchanges',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/support',
        title: 'FAQ',
        menu: 'Support',
        label: 'FAQ',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/kadenajs',
        title: 'Running Tests',
        menu: 'KadenaJS',
        label: 'Running Tests',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/resources',
        title: 'Kadena Resources',
        menu: 'Resources',
        label: 'Resources',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/client',
        title: 'Package @kadena/client',
        menu: 'Client',
        label: 'Package @kadena/client',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/client-examples',
        title: 'Client examples',
        menu: 'Client examples',
        label: 'Client examples',
        isMenuOpen: false,
        isActive: false,
      },
      {
        children: [],
        root: '/docs/kadena/code-of-conduct',
        menu: 'Code of Conduct',
        title: 'Code of Conduct',
        label: 'Code of Conduct',
        isMenuOpen: false,
        isActive: false,
      },
    ],
    root: '/docs/kadena',
    title: 'Intro to Kadena',
    menu: 'Kadena',
    label: 'Introduction',
    isMenuOpen: true,
    isActive: false,
  },
  {
    root: '/docs/build',
    title: 'Build on Kadena',
    menu: 'Build',
    label: 'Introduction',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/pact',
    title: 'Learn Pact',
    menu: 'Pact',
    label: 'Pact',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/contribute',
    title: 'Contribute',
    menu: 'Contribute',
    label: 'Contribute',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/chainweb',
    title: 'Intro to Chainweb',
    menu: 'Chainweb',
    label: 'Introduction',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/marmalade',
    title: 'Intro to Marmalade',
    menu: 'Marmalade',
    label: 's',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
  {
    root: '/docs/blogchain',
    title: 'BlogChain',
    menu: 'BlogChain',
    label: 'BlogChain',
    isMenuOpen: false,
    isActive: false,
    children: [],
  },
];
