'use client';
import { SideBarLayout } from '@kadena/kode-ui/patterns';

import { Link, mediaProviderStyles } from '@kadena/kode-ui';
import { KLogo } from './KLogo';
import { Providers } from './Providers';
import { SideBar } from './SideBar';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const RootLayout = ({
  children,
	@@ -12,7 +18,27 @@ const RootLayout = ({
}>) => {
  return (
    <html lang="en">
      <head>
        <style
          key="fresnel-css"
          dangerouslySetInnerHTML={{ __html: mediaProviderStyles }}
          type="text/css"
        />
      </head>
      <body>
        <Providers>
          <SideBarLayout
            logo={
              <Link href="/">
                <KLogo height={40} />
              </Link>
            }
            sidebar={<SideBar />}
          >
            {children}
          </SideBarLayout>
        </Providers>
      </body>
    </html>
  );