services:
  mcp-server:
    image: mcr.microsoft.com/playwright/mcp:latest
    command: >
      --config /.claude/settings.json
    ports:
      - '3000:3000'
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - claude-network
    volumes:
      - ./claude-config.json:/.claude/settings.json

  claude-cli:
    build: .
    depends_on:
      - mcp-server
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_CONFIG_FILE=/.claude/settings.json
      - MCP_SERVER_URL=http://mcp-server:3000
    volumes:
      - .:/app
      - ./claude-config.json:/.claude/settings.json
    networks:
      - claude-network
    stdin_open: true
    tty: true
    command: >
      bash -c "
       claude -p 'Navigate to straatemans.nl and take a screenshot of the
      homepage.'
      --output-format json --permission-mode plan --allowedTools
      'mcp__playwright__browser_snapshot, mcp__playwright__browser_navigate,
      mcp__playwright__browser_take_screenshot'"
networks:
  claude-network:
    driver: bridge
