/* This file is generated automatically by Design Sync. Do not edit this file directly. */

import { style } from '@vanilla-extract/css';

import { tokens } from './contract.css';

/**
 * Small Code @xs Description
 */
export const monospaceSmallRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
  },
});

/**
 * Small Code Bold @ xs Description
 */
export const monospaceSmallBold = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.bold,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
  },
});

/**
 * Smallest Code @xs Description
 */
export const monospaceSmallestRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xxs,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.sm,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
  },
});

/**
 * Smallest Code Bold @ xs Description
 */
export const monospaceSmallestBold = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xxs,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.bold,
  lineHeight: tokens.kda.foundation.typography.lineHeight.sm,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
  },
});

/**
 * Code @xs Description
 */
export const monospaceBaseRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.sm,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.regular,
  lineHeight: '1.125rem',
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});

/**
 * Code Bold @ xs Description
 */
export const monospaceBaseBold = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.sm,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.bold,
  lineHeight: '1.125rem',
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});

/**
 * H1 Description
 */
export const typographyFontH1 = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize['3xl'],
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight['4xl'],
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['5xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['7xl'],
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['5xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['7xl'],
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['5xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['7xl'],
    },
  },
});

/**
 * H2 Description
 */
export const typographyFontH2 = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize['2xl'],
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight['3xl'],
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['3xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['4xl'],
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['3xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['4xl'],
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['3xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['4xl'],
    },
  },
});

/**
 * H3 Description
 */
export const typographyFontH3 = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xl,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight['2xl'],
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['2xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['3xl'],
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['2xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['3xl'],
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize['2xl'],
      lineHeight: tokens.kda.foundation.typography.lineHeight['3xl'],
    },
  },
});

/**
 * H4 Description
 */
export const typographyFontH4 = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.lg,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xl,
      lineHeight: tokens.kda.foundation.typography.lineHeight['2xl'],
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xl,
      lineHeight: tokens.kda.foundation.typography.lineHeight['2xl'],
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xl,
      lineHeight: tokens.kda.foundation.typography.lineHeight['2xl'],
    },
  },
});

/**
 * H5 Description
 */
export const typographyFontH5 = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.base,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight.base,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.lg,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.lg,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.lg,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
  },
});

/**
 * H6 Description
 */
export const typographyFontH6 = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.sm,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: '1.125rem',
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});

/**
 * Input Element Code @xs Description
 */
export const inputMonospaceBaseRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 40rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.125rem',
    },
    '(width >= 48rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});

/**
 * Input Element Code @xs Description
 */
export const inputMonospaceMobileRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.monospaceFont,
  fontSize: tokens.kda.foundation.typography.fontSize.base,
  fontWeight: tokens.kda.foundation.typography.weight.monospaceFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.base,
  letterSpacing: tokens.kda.foundation.spacing.n0,
});

/**
 * Input Element @xs Description
 */
export const inputUiBaseRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 40rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.375rem',
    },
    '(width >= 48rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
  },
});

/**
 * Input Element @xs Description
 */
export const inputUiMobileRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.base,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
  letterSpacing: tokens.kda.foundation.spacing.n0,
});

/**
 * Small P @xs Description
 */
export const bodySmallRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.secondaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.secondaryFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.375rem',
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.375rem',
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.375rem',
    },
  },
});

/**
 * Small P Bold @ xs Description
 */
export const bodySmallBold = style({
  fontFamily: tokens.kda.foundation.typography.family.secondaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.secondaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.375rem',
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.375rem',
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
      lineHeight: '1.375rem',
    },
  },
});

/**
 * Smallest P @xs Description
 */
export const bodySmallestRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.secondaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xxs,
  fontWeight: tokens.kda.foundation.typography.weight.secondaryFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});

/**
 * Smallest P Bold @ xs Description
 */
export const bodySmallestBold = style({
  fontFamily: tokens.kda.foundation.typography.family.secondaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xxs,
  fontWeight: tokens.kda.foundation.typography.weight.secondaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});

/**
 * P @xs Description
 */
export const bodyBaseRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.secondaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.sm,
  fontWeight: tokens.kda.foundation.typography.weight.secondaryFont.regular,
  lineHeight: '1.375rem',
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
  },
});

/**
 * P Bold @ xs Description
 */
export const bodyBaseBold = style({
  fontFamily: tokens.kda.foundation.typography.family.secondaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.sm,
  fontWeight: tokens.kda.foundation.typography.weight.secondaryFont.medium,
  lineHeight: '1.375rem',
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.xl,
    },
  },
});

/**
 * Small P @xs Description
 */
export const uiSmallRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
  },
});

/**
 * Small P Bold @ xs Description
 */
export const uiSmallBold = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xs,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight.md,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.sm,
    },
  },
});

/**
 * Smallest P @xs Description
 */
export const uiSmallestRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xxs,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.regular,
  lineHeight: tokens.kda.foundation.typography.lineHeight.sm,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
  },
});

/**
 * Smallest P Bold @ xs Description
 */
export const uiSmallestBold = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.xxs,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: tokens.kda.foundation.typography.lineHeight.sm,
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.xs,
      lineHeight: tokens.kda.foundation.typography.lineHeight.md,
    },
  },
});

/**
 * P @xs Description
 */
export const uiBaseRegular = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.sm,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.regular,
  lineHeight: '1.125rem',
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});

/**
 * P Bold @ xs Description
 */
export const uiBaseBold = style({
  fontFamily: tokens.kda.foundation.typography.family.primaryFont,
  fontSize: tokens.kda.foundation.typography.fontSize.sm,
  fontWeight: tokens.kda.foundation.typography.weight.primaryFont.medium,
  lineHeight: '1.125rem',
  letterSpacing: tokens.kda.foundation.spacing.n0,
  '@media': {
    '(width >= 64rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 80rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
    '(width >= 96rem)': {
      fontSize: tokens.kda.foundation.typography.fontSize.base,
      lineHeight: tokens.kda.foundation.typography.lineHeight.base,
    },
  },
});
