import './Query/account';
import './Query/block';
import './Query/blocksFromHeight';
import './Query/chainAccount';
import './Query/completedBlockHeights';
import './Query/gasLimitEstimate';
import './Query/graphConfiguration';
import './Query/lastBlockHeight';
import './Query/pactQuery';
import './Query/transactionByPublicKey';
import './Query/transactions';
import './Query/transfers';
import './Subscription/event';
import './Subscription/newBlocks';
import './Subscription/transaction';
import { builder } from './builder';
import './objects/Block';
import './objects/Event';
import './objects/GraphConfiguration';
import './objects/Guard';
import './objects/MinerKey';
import './objects/Signer';
import './objects/TotalCount';
import './objects/Transaction';
import './objects/Transfer';
import './objects/chain-fungible-account';
import './objects/fungible-account';
builder.queryType({});
// no mutation fields defined yet, hence commented
// builder.mutationType({});
builder.subscriptionType({});
