name: Update Chainweb-node Changelogs

on:
  workflow_dispatch:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-changelog:
    name: Update Chainweb-node Changelogs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Runner setup
        uses: ./.github/actions/runner-setup

      - name: Build Docs Tools
        run:  pnpm turbo build --filter @kadena/docs-tools

      - name: Update chainweb-node changelog
        run: pnpm run docs:changelogs
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.RELEASE_ACTION_GITHUB_TOKEN }}
          commit-message: Update Chainweb-node Changelogs
          title: Update Chainweb-node Changelogs
          body: |
            This PR updates the Chainweb-node changelogs.
          branch: update-chainweb-node-changelogs
          base: main
          reviewers: |
            @sstraatemans
          assignees: |
            @sstraatemans 

     
