name: CI (contains changelog update?)

on:
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}
          cache: 'pnpm'

      - name: Contains changelog update?
        run: pnpx @changesets/cli status --since origin/main
