name: Integration Tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: kadena/devnet
        options: >-
          -t
          --memory 7g
          --cpus 2
          --health-cmd "curl --silent --fail http://127.0.0.1:8080/info || exit 1"
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: pnpm install
        run: pnpm install

      - name: pnpm build
        run: pnpm --filter @kadena/client build

      - name: pnpm test:integration
        run: pnpm --filter @kadena/client test:integration
