name: Integration Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: node:18

    services:
      devnet:
        image: enof/devnet
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd "/bin/bash -c exec 3<>/dev/tcp/localhost/1848; printf "GET /health-check HTTP/1.1\r\nhost: http://localhost:1848\r\nConnection: close\r\n\r\n" >&3; grep -q "200 OK" <&3 || exit 1"
          --health-interval 30s
          --health-timeout 30s
          --health-retries 5
          --health-start-period 2m
          --memory 7g
        ports:
          - 8080:1337

    steps:
        - name: check devnet health
          uses: jtalk/url-health-check-action@v3
          with:
            url: http://localhost:8080/info
            # Follow redirects, or just report success on 3xx status codes
            max-attempts: 20 # Optional, defaults to 1
            # Delay between retries
            retry-delay: 5s # Optional, only applicable to max-attempts > 1




