name: Integration Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: enof/devnet
        env:
          PC_DISABLE_TUI: true
        # Set health checks to wait until postgres has started
        options: >-
          -a STDOUT
          -t
          --memory 7g
          --cpus 2
          --health-cmd "curl --silent --fail http://devnet:1337/info || exit 1"
        ports:
          - 8080:1337

    steps:
#        - name: Sleep for 10s
#          uses: juliangruber/sleep-action@v2.0.0
#          with:
#            time: 300s
#        - name: Rush format (install-run-rush)
#          run: |
#            docker ps -a
        - name: check devnet health
          uses: jtalk/url-health-check-action@v3
          with:
            url: http://devnet:8080/info
            # Follow redirects, or just report success on 3xx status codes
            max-attempts: 20 # Optional, defaults to 1
            # Delay between retries
            retry-delay: 5s # Optional, only applicable to max-attempts > 1




