name: Integration Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: enof/devnet
        options: >-
          -t
          --memory 7g
          --cpus 2
          --health-cmd "curl --silent --fail http://devnet:1337/info || exit 1"
        ports:
          - 8080:1337

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 2
        # TODO: Replace this with a decent unit test
        - name: Fund Account
          run: docker run --rm -v $(pwd):/app/ --add-host=devnet:host-gateway enof/kda-cli --profile=.fund-profile.json
          working-directory: packages/tools/integration-tests




