name: Integration Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: enof/devnet
        options: >-
          --memory=8g
        ports:
          - 8080:1337



    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Rush install (install-run-rush)
        run: |
          node common/scripts/install-run-rush.js install

      - name: Rush test (install-run-rush)
        run: |
          node common/scripts/install-run-rush.js test -t @kadena/integration-tests



