name: Integration Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: enof/devnet
        ports:
          - 1337:1337



    steps:
        - name: check devnet health
          uses: jtalk/url-health-check-action@v3
          with:
            url: http://localhost:1337/info
            # Follow redirects, or just report success on 3xx status codes




