name: Integration Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: enof/devnet
        options: >-
          -m 7g
        ports:
          - 8080:1337



    steps:
        - name: Wait for the database to start
          run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- localhost:8080/info -- echo "Devnet up"
          env:
            WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
        - name: check devnet health
          uses: jtalk/url-health-check-action@v3
          with:
            url: http://localhost:8080/info
            # Follow redirects, or just report success on 3xx status codes
            max-attempts: 20 # Optional, defaults to 1
            # Delay between retries
            retry-delay: 10 # Optional, only applicable to max-attempts > 1




