name: React UI Storybook Tests

# All pull requests, and
# Workflow dispatch allows you to run this workflow manually from the Actions tab
on:
  pull_request:
    paths:
      - packages/libs/react-ui/**
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/libs/react-ui/**


jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Rush install (install-run-rush)
        run: |
          node common/scripts/install-run-rush.js install -t @kadena/react-ui

      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
          allow_inactive: true
        # access preview url
      - run: echo ${{steps.waitForPreview.outputs.url}}

      - name: Smoke Tests
        working-directory: packages/libs/react-ui
        run: |
           npm run test:storybook
        env:
          TARGET_URL: '${{steps.waitForPreview.outputs.url}}'
