name: React UI Storybook Tests

# All pull requests, and
# Workflow dispatch allows you to run this workflow manually from the Actions tab
on:
  workflow_run:
    workflows: ["Rush CI (changelog, build, test)"]
    types:
      - completed


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 200
          allow_inactive: true
          # access preview url
      - run: echo ${{steps.waitForPreview.outputs.url}}

      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Rush install (install-run-rush)
        run: |
          node common/scripts/install-run-rush.js install -t @kadena/react-ui

      - name: Smoke Tests
        working-directory: packages/libs/react-ui
        run: |
           npm run test:storybook


